### ISSUE TITLE
Type Error when attempting to load server

### ISSUE THREAD

**Issue by AdmiralSimonn** [KillerDJLang/Raid-Overhaul#27]
"TypeError: Cannot read properties of undefined (reading 'Filter')
TypeError: Cannot read properties of undefined (reading 'Filter')
    at D:\A SPT\user\mods\RaidOverhaul\src\CustomItems\ItemGenerator.ts:324:61
    at Array.forEach (<anonymous>)
    at ItemGenerator.addToCases (D:\A SPT\user\mods\RaidOverhaul\src\CustomItems\ItemGenerator.ts:317:45)
    at ItemGenerator.createCustomItems (D:\A SPT\user\mods\RaidOverhaul\src\CustomItems\ItemGenerator.ts:70:14)
    at RaidOverhaul.loadCustomItems (D:\A SPT\user\mods\RaidOverhaul\src\mod.ts:221:21)
    at RaidOverhaul.postDBLoad (D:\A SPT\user\mods\RaidOverhaul\src\mod.ts:177:10)
    at PostDBModLoader.executeModsAsync (C:\snapshot\src\loaders\PostDBModLoader.ts:63:45)
    at PostDBModLoader.onLoad (C:\snapshot\src\loaders\PostDBModLoader.ts:26:24)
    at App.load (C:\snapshot\src\utils\App.ts:53:26)
TypeError: Cannot read properties of undefined (reading 'Filter')
TypeError: Cannot read properties of undefined (reading 'Filter')
    at D:\A SPT\user\mods\RaidOverhaul\src\CustomItems\ItemGenerator.ts:324:61
    at Array.forEach (<anonymous>)
    at ItemGenerator.addToCases (D:\A SPT\user\mods\RaidOverhaul\src\CustomItems\ItemGenerator.ts:317:45)
    at ItemGenerator.createCustomItems (D:\A SPT\user\mods\RaidOverhaul\src\CustomItems\ItemGenerator.ts:70:14)
    at RaidOverhaul.loadCustomItems (D:\A SPT\user\mods\RaidOverhaul\src\mod.ts:221:21)
    at RaidOverhaul.postDBLoad (D:\A SPT\user\mods\RaidOverhaul\src\mod.ts:177:10)
    at PostDBModLoader.executeModsAsync (C:\snapshot\src\loaders\PostDBModLoader.ts:63:45)
    at PostDBModLoader.onLoad (C:\snapshot\src\loaders\PostDBModLoader.ts:26:24)
    at App.load (C:\snapshot\src\utils\App.ts:53:26)"

**Comment by iam-thedude** [comment]
Today suddenly the exact same error appeared
Reinstalling is not helping

**Comment by KillerDJLang** [comment]
Turn off case space manager (csm) in svm.
Idk what other mods would cause this issue but I know svm will.
I'll work on a permanent fix at some point.

**Comment by iam-thedude** [comment]
> Turn off case space manager (csm) in svm. Idk what other mods would cause this issue but I know svm will. I'll work on a permanent fix at some point.

Hi! No effect. thanks

![image](https://github.com/user-attachments/assets/a6b7c41b-bcb5-4bdd-a7aa-e1ddf7706ba5)

My gues is that SPT AKI Profile editor messed something after its initial setup. I made no saved changes in Profile editor i just chose my game location

Restoring profile from backup is not helping

**Comment by iam-thedude** [comment]
> Turn off case space manager (csm) in svm. Idk what other mods would cause this issue but I know svm will. I'll work on a permanent fix at some point.

Sooo, your text about CSM made me think in that direction and the problem was with Configurable Inventories config file about secure containers. Reverting those changes fixed the error

**Comment by KillerDJLang** [comment]
Should be fixed in a more permanent fashion now
