### ISSUE TITLE
Opening weapon case

### ISSUE THREAD

**Issue by FirefighterKyle** [KillerDJLang/Raid-Overhaul#8]
```
TypeError: Cannot read properties of undefined (reading 'resolve')
TypeError: Cannot read properties of undefined (reading 'resolve')
    at Function.customOpenRandomLootContainer (F:\sptark\user\mods\zDJsRaidOverhaul\src\mod.ts:429:41)
    at InventoryCallbacks.openRandomLootContainer (F:\sptark\user\mods\zDJsRaidOverhaul\src\mod.ts:69:37)
    at InventoryItemEventRouter.handleItemEvent (C:\snapshot\project\src\routers\item_events\InventoryItemEventRouter.ts:91:48)
    at ItemEventRouter.handleEvents (C:\snapshot\project\src\routers\ItemEventRouter.ts:42:38)
    at ItemEventCallbacks.handleEvents (C:\snapshot\project\src\callbacks\ItemEventCallbacks.ts:26:52)
    at RouteAction.action (C:\snapshot\project\src\routers\static\ItemEventStaticRouter.ts:17:52)
    at ItemEventStaticRouter.handleStatic (C:\snapshot\project\src\di\Router.ts:50:63)
    at HttpRouter.handleRoute (C:\snapshot\project\src\routers\HttpRouter.ts:79:62)
    at HttpRouter.getResponse (C:\snapshot\project\src\routers\HttpRouter.ts:44:30)
    at AkiHttpListener.getResponse (C:\snapshot\project\src\servers\http\AkiHttpListener.ts:150:38)
TypeError: Cannot read properties of undefined (reading 'resolve')
TypeError: Cannot read properties of undefined (reading 'resolve')
    at Function.customOpenRandomLootContainer (F:\sptark\user\mods\zDJsRaidOverhaul\src\mod.ts:429:41)
    at InventoryCallbacks.openRandomLootContainer (F:\sptark\user\mods\zDJsRaidOverhaul\src\mod.ts:69:37)
    at InventoryItemEventRouter.handleItemEvent (C:\snapshot\project\src\routers\item_events\InventoryItemEventRouter.ts:91:48)
    at ItemEventRouter.handleEvents (C:\snapshot\project\src\routers\ItemEventRouter.ts:42:38)
    at ItemEventCallbacks.handleEvents (C:\snapshot\project\src\callbacks\ItemEventCallbacks.ts:26:52)
    at RouteAction.action (C:\snapshot\project\src\routers\static\ItemEventStaticRouter.ts:17:52)
    at ItemEventStaticRouter.handleStatic (C:\snapshot\project\src\di\Router.ts:50:63)
    at HttpRouter.handleRoute (C:\snapshot\project\src\routers\HttpRouter.ts:79:62)
    at HttpRouter.getResponse (C:\snapshot\project\src\routers\HttpRouter.ts:44:30)
    at AkiHttpListener.getResponse (C:\snapshot\project\src\servers\http\AkiHttpListener.ts:150:38)
```

Not sure what could be causing it?

**Comment by KillerDJLang** [comment]
Do you have Viktoriya the gambler or Just NUs Enhanced Loot Bag API installed?

**Comment by FirefighterKyle** [comment]
I don't have either one, could that be my issue?
All I have is, True Items, Bandana of protection and your mod.

**Comment by KillerDJLang** [comment]
Nah, those are the only two mods I know of that could/do conflict with my loot boxes.
Don't know if maybe true items could be messing with them but I'll test quick and double check I didn't mess something up in my last update.

**Comment by FirefighterKyle** [comment]
Thanks, I didn't try to open the second one I got in-raid, just in case it would crash me. When I got the first one, I thought it was just a weapons case to put guns in. When I tried to open it in my stash, that is when it gave me the errors.

**Comment by KillerDJLang** [comment]
Yeah, just tested and I broke something lol.
I'm going to check if it's all the cases and then work on a fix

**Comment by FirefighterKyle** [comment]
Good to know it wasn't something I did 😂 thanks for checking.

**Comment by KillerDJLang** [comment]
Fixed it.
Just added a few more things in so I'll test those and then upload the new version!

Thanks for the report, will close up this issue now :)
